### ISSUE TITLE
PreferenceFragment

### ISSUE THREAD

**Issue by nmesisca** [MrBIMC/MaterialSeekBarPreference#10]
Hi there,
I was wondering if you have tested this in a preferenceFragment, as my implementation doesn't seem to save the preferences at all.

thanks for your help,
N

**Comment by MrBIMC** [comment]
Sorry, my bad. Feels like I broke it in v0.11. I will release v0.12 in a couple of minutes!

**Comment by MrBIMC** [comment]
Just pushed new version with fix to mavencentral. Update your reference to 0.12

**Comment by nmesisca** [comment]
Thanks seems all good now!
What are you planning next for this library? any new features in the work?

**Comment by MrBIMC** [comment]
Well, I honestly didn't plan to go past first release. But as you see new features are always being requested + new bugs appear because I'm to lazy to test new features before publishing update :disappointed:
