### ISSUE TITLE
defaultValue

### ISSUE THREAD

**Issue by nmesisca** [MrBIMC/MaterialSeekBarPreference#11]
Hi again,
I'm on 0.12 and using this on a PreferenceFragment .. defaultValue doesn't seem to be working as the seekbar seems to be set to max when defaults should be applied.

<com.pavelsikun.seekbarpreference.SeekBarPreference
        android:key="drops"
        android:title="Drops"
        android:summary="@string/pref_drops"
        android:enabled="true"
        android:defaultValue="20"
        sample:msbp_minValue="1"
        sample:msbp_maxValue="40"
        sample:msbp_interval="1"
        sample:msbp_measurementUnit="drops">
    </com.pavelsikun.seekbarpreference.SeekBarPreference>

thanks for your help!
N

**Comment by MrBIMC** [comment]
OMG, sorry lol. Once again, it's a post-v11 bug because of my derps. Will fix soon :D

**Comment by MrBIMC** [comment]
BTW, for now you can roll back to v0.10, It has completely the same API, but everything works. Only difference is that it doesn't support Views, but i'm pretty sure you don't need them

**Comment by nmesisca** [comment]
cool thanks. I will revert to 0.10 until you have this fixed.

**Comment by MrBIMC** [comment]
actually I just thought that I might even split View && Preference things into separate libraries, because supporting both with a single code-base is hacky(due to overlap in xml tags) and useless. Those who need Preference won't use View and vice-versa.

**Comment by nmesisca** [comment]
I agree its probably a good idea. Looking forwards to your next version then!
