### ISSUE TITLE
How to Fix Error inflating class com.pavelsikun.seekbarpreference.SeekBarPreference

### ISSUE THREAD

**Issue by Docker-J** [MrBIMC/MaterialSeekBarPreference#12]
my preference.xml

<PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:sample="http://schemas.android.com/apk/res-auto">>

```
<com.pavelsikun.seekbarpreference.SeekBarPreference
    android:key="your_pref_key"
    android:title="Sensibility"
    android:enabled="false"
    android:defaultValue="5000"
    sample:msbp_minValue="100"
    sample:msbp_maxValue="60"
    sample:msbp_interval="200"
    sample:msbp_measurementUnit="G"/>

<com.pavelsikun.seekbarpreference.SeekBarPreference
    android:key="your_pref_key"
    android:title="Number Of Shake"
    android:summary="Some summary"
    android:enabled="false"
    android:defaultValue="5000"
    sample:msbp_minValue="100"
    sample:msbp_maxValue="10000"
    sample:msbp_interval="200"/>
```

</PreferenceScreen>

Fragment

public class SettingsFragment extends PreferenceFragmentCompat  {

```
SeekBar sensibility;
TextView sensibility_label;
SeekBar shakeTime;
TextView shakeTime_label;

@Override
public void onCreatePreferences(Bundle savedInstanceState, String rootKey) {
    addPreferencesFromResource(R.xml.settings);
}
```

}

gradle

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.makeramen:roundedimageview:2.2.0'
    compile 'com.google.android.gms:play-services:8.1.0'
    compile 'com.android.support:design:23.0.1'
    compile 'com.android.support:preference-v7:23.0.1'
    compile 'com.android.support:preference-v14:23.0.1'
    compile 'com.pavelsikun:material-seekbar-preference:0.11'
}

How can I solve this problem?

**Comment by tylerwilson** [comment]
You do not show the exact error, but I suspect it is the same cause as issue #24. See my description there.

**Comment by hiworld75018** [comment]
I have the same error:

```
Error inflating class com.pavelsikun.seekbarpreference.SeekBarPreference
at android.support.v7.preference.PreferenceInflater.createItem(PreferenceInflater.java:262)
...
Caused by: java.lang.ClassCastException: com.pavelsikun.seekbarpreference.SeekBarPreference
cannot be cast to android.support.v7.preference.Preference
```

I'm using AppCompat / PreferenceFragmentCompat. How about switching to android.support.v7.preference.Preference to support older devices ?

**Comment by MrBIMC** [comment]
I have supporting v7+ in plans, but don't have time right now.

**Comment by MrBIMC** [comment]
New update now supports v7+ :D
