### ISSUE TITLE
Marshmallow issue with seekbar drag

### ISSUE THREAD

**Issue by nmesisca** [MrBIMC/MaterialSeekBarPreference#13]
Hi there.
I'm on 0.12, not the latest , but I wanted to report that dragging the seekbar doesn't seem to be working for me on marshmallow. Same code runs fine on lollipop.

Thanks for the help,
N

**Comment by nmesisca** [comment]
Just wanted to add I seem to be having the same issue on my emulator running 4.1.1

**Comment by andreavico** [comment]
Testing on a Nexus 5 running Marshmallow, I haven't encountered any problem.

**Comment by nmesisca** [comment]
Have you tested preference or view? My issue seems to be with preference seekbar..
my same code runs fine on lollipop and has the issue on marshmallow

**Comment by andreavico** [comment]
I have been using the Preference as well.

**Comment by nmesisca** [comment]
@Andreaaa would you be so kind as to let me have a peek at how you have it implemented in preferences please? I can't understand if I am doing something wrong and how could my code work well on 5.1.1 but not on 6. At this stage any help would be welcome! cheers.

**Comment by andreavico** [comment]
@nmesisca I've simply put it into my preference xml file:

<PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android" xmlns:seekbar="http://schemas.android.com/apk/res-auto">

```
<PreferenceCategory 
    android:title="@string/pref_header_behavior"
    android:key="behavior">

    <com.pavelsikun.seekbarpreference.SeekBarPreference
        android:key="workSessionDuration"
        android:title="@string/pomowork_length"
        android:defaultValue="25"
        seekbar:msbp_minValue="1"
        seekbar:msbp_maxValue="60"
        seekbar:msbp_interval="1"
        seekbar:msbp_measurementUnit="@string/minutes"/>
```

But what do you mean it's not working for you?

**Comment by nmesisca** [comment]
@Andreaaa thanks for coming back to me mate. The only thing that could cause some problem might be the fact that I am using the AppCompatDelegate in order to have tinting on older versions of Android.
In the specific, the issue is that on 6.0 dragging the seekbar causes it only to move of 1 interval, then it stops, forcing you to drag it again and again to make it move. the exact same apk when run on 5.x is flawless. My implementation is very standard, pretty much like yours so I dont' see how I could have caused this to happen.
If anyone is willing to give this library a run using AppCompatDelegate it would be very appreciated.
Also any input from @MrBIMC would be great.
Thanks guys for the help,
N

**Comment by MrBIMC** [comment]
Should be fixed in the latest release. Though I tested only on api-14+.
