### ISSUE TITLE
API 11 needed?

### ISSUE THREAD

**Issue by midramas** [MrBIMC/MaterialSeekBarPreference#15]
Do you really need API level 11? I want to use it in my app, but it's API 8 :( Br, Michael

**Comment by mtotschnig** [comment]
I have created a fork of this library that is based on preference-v7 support library and supports API 8.

**Comment by midramas** [comment]
Thx for letting me know! I will give it a try :)

**Comment by MrBIMC** [comment]
Just released an update with support of v7 and up! Wooo!
