### ISSUE TITLE
Ability to disable EditText

### ISSUE THREAD

**Issue by basitsaeed** [MrBIMC/MaterialSeekBarPreference#18]
This library has helped me a lot in implementing a pretty common preference pattern. I do have a small request, however. Can you please add the ability to disable EditText, i.e. can we just use it as a label that just changes when you drag the seekbar. 
Thanks.

**Comment by MrBIMC** [comment]
@mehmetakiftutuncu already implemented it, I will merge his PR(https://github.com/MrBIMC/MaterialSeekBarPreference/pull/25) tomorrow. 

Also will make underline below valueHolder invisible if customInputDialog is not enabled.

**Comment by MrBIMC** [comment]
v2.2.0 released(though it might take a while while it appears on jcenter) with this and a bit more!
