### ISSUE TITLE
Getting current value from the seekbar 

### ISSUE THREAD

**Issue by Em3ka** [MrBIMC/MaterialSeekBarPreference#2]
I followed your instructions as regards setting the seekbar in my app and got it referenced nicely. My issue is that I can't get the value set by the seekbar from sharedpreference in an activity. Your "how-to" only shows how to setup the Preference XML file, what about using that set value in an activity?

**Comment by MrBIMC** [comment]
@chilldelta this works for me:
int val = PreferenceManager.getDefaultSharedPreferences(this).getInt("seekbar_key", 0);

Or am I not understand your question correctly?

**Comment by chilldelta** [comment]
Yes. That's what I did but I get a ResourcesNotFoundException. Any clue solving this?

**Comment by Sicness** [comment]
@MrBIMC But how get be notified when an user changed the value? i'd like to react on the change. Unfortunately example doesn't content such typical situation... setOnPreferenceChangeListener for some reason doesn't work for me.
