### ISSUE TITLE
Cannot set defaultValue in Android 6.x?

### ISSUE THREAD

**Issue by einverne** [MrBIMC/MaterialSeekBarPreference#22]
I define SeekBarPreference like this:

```
    <com.pavelsikun.seekbarpreference.SeekBarPreference
        android:key="sizeOfCircle"
        android:title="x"
        android:summary="x"
        android:defaultValue="30"
        android:enabled="true"
        app:msbp_maxValue="100"
        app:msbp_minValue="1"
        app:msbp_interval="1"
        />
```

However, I found the default value is always 50.

I am using `compile 'com.pavelsikun:material-seekbar-preference:0.12.1+'`

**Comment by einverne** [comment]
It seems duplicated as #11

**Comment by ashleypeacock** [comment]
One solution is to revert to before the author made some big changes as in #11.

I don't have this issue - defaults for me are working. I'm using 3 different seek bars and they're working in every case.

 I'm **not** using 

`compile 'com.pavelsikun:material-seekbar-preference:0.12.1+`

but downloading and compiling the project directly.
