### ISSUE TITLE
Negative values

### ISSUE THREAD

**Issue by aseolin** [MrBIMC/MaterialSeekBarPreference#3]
Hello. When I try to put negative values to min/max, the seekbar goes to zero (but the value in summary is ok). Here is my config

<com.pavelsikun.seekbarpreference.SeekBarPreference
            android:key="power"
            android:title="@string/power"
            android:summary="@string/power_exp"
            android:defaultValue="-20"
            materialdesign:minValue="-80"
            materialdesign:maxValue="-30"
            materialdesign:interval="1"
            materialdesign:measurementUnit="@string/dbm" />

**Comment by MrBIMC** [comment]
I will look to it. The main problem is that android's seekbar itself doesn't support negative values. It's solvable though :D

**Comment by aseolin** [comment]
Thank you MrBIMC

**Comment by MrBIMC** [comment]
Fixed!
Release 0.8 is out, grab it now by updating lib reference to 

``` Groovy
compile 'com.pavelsikun:material-seekbar-preference:0.8+'
```

Changes:
- added support for negative values;
- getValue and setValue public methods;
- fixed default seekbar value indication;
