### ISSUE TITLE
Set default value

### ISSUE THREAD

**Issue by aseolin** [MrBIMC/MaterialSeekBarPreference#5]
I'm trying to set my SeekBarPreference default value, but I don't know how to do that. In a ListPreference, for example, I can do something like this:

  ListPreference lp= (ListPreference) findPreference("list_preference");
  if(lp.getValue() == null) {
    lp.setValue("2");
  }

How to do that in a SeekBarPreference?

**Comment by MrBIMC** [comment]
For now it's:

``` Java
SeekBarPreference pref = (SeekBarPreference) findPreference(KEY_VIBRATION);
pref.persistInt(trigger.getVibration());
```

Sorry for unobviousness. Also, as far as I see, you can't get value directly from preference, so you have to access it by key via PreferenceManager.

I will provide 2 new methods in the next update then: getValue and setValue.

**Comment by aseolin** [comment]
Thank you MrBIMC. In this upcoming update, could you implement the option to allow negative values in the seekbar?

**Comment by MrBIMC** [comment]
I will(Actually, I already did :D). I will test few things and release update soon!

**Comment by MrBIMC** [comment]
Fixed!
Release 0.8 is out, grab it now by updating lib reference to 

``` Groovy
compile 'com.pavelsikun:material-seekbar-preference:0.8+'
```

Changes:
- added support for negative values;
- getValue and setValue public methods;
- fixed default seekbar value indication;

**Comment by aseolin** [comment]
Works like a charm! Thank you!!!
