### ISSUE TITLE
Class cast exception

### ISSUE THREAD

**Issue by robross0606** [MrBIMC/MaterialSeekBarPreference#59]
Getting an exception when adding this to my Preferences:
`com.pavelsikun.seekbarpreference.SeekBarPreference cannot be cast to android.support.v7.preference.Preference`

**Comment by robross0606** [comment]
Nevermind, I was not using the correct "Compat" class.

**Comment by Arunm619** [comment]
How did you fix this issue? Can you elaborate pls? @robross0606
