### ISSUE TITLE
Create methods for programmatic use

### ISSUE THREAD

**Issue by danialgoodwin** [MrBIMC/MaterialSeekBarPreference#7]
This is an enhancement request, for Java method equivalents for the XML attributes. It'll take awhile for me to get time for it, so I'm leaving it open for anybody now.

My use case: Lately-ish, I've been minimizing XML use, and mostly only using XML as "content holders" for various configurations with all the content being added programmatically. Also, it allows for easier A/B testing by changing values dynamically over network rather than recompiling in different static values.

**Comment by MrBIMC** [comment]
Well, that's simpler than fixing focus issues

I will look to it soon :D

**Comment by MrBIMC** [comment]
FIXED!
I was sorta bored, so release is already here, check sample app and release info for additional information ( https://github.com/MrBIMC/MaterialSeekBarPreference/releases/tag/0.9 )

**Comment by danialgoodwin** [comment]
Awesome! Thank you very much!
