### ISSUE TITLE
Why not a View ??

### ISSUE THREAD

**Issue by srmdev29** [MrBIMC/MaterialSeekBarPreference#9]
You did a great job ! why not a view ...But It would be better if we can able to add a view to existing layout. .

**Comment by MrBIMC** [comment]
In most cases people use default implementation of preferences, which are built upon PreferenceFragment. I will think on moving render code to external View as it's quite simple task, but honestly, I see no cases why would anyone use SeekBarPreference as a View and not as a preference.

**Comment by srmdev29** [comment]
Its useful when we try to implement a filter functionality.Examples : Price range

**Comment by MrBIMC** [comment]
I just published v0.11 that also contains view component that acts the same way as preference :D
